### PR TITLE
Gz before sync

### PR DESCRIPTION
**Pull request by jonakarl**
This is a "minimal change" approach to enable compression. 

Proably some more tweaks that needs to be done before it is finished. 

Alternative solution (possibly more general) :
Skip the manual merging of the json files and use tar +bz2 ... not sure which is cleanest

### CODE REVIEW

**Comment by relet** [comment]
How does the transfer size compare against rsync --compress?

**Comment by relet** [comment]
Also, don't we lose any advantage rsync may have over scp if we are guaranteed to have a different file every time?

**Comment by jonakarl** [comment]
rsync --compress vz bzip2 => do not know .... we have to test (I think Mike did this before the summer and he said he could see substantial gains). I will do a simple test today and see possible gains. 

We do not have a different file every time .... we only compress json files .... the ones that are already compressed are kept as is. Or did I misunderstand you?

**Comment by relet** [comment]
Ah, I see. I somehow imagined that they were all compressed into a single archive. My bad.
rsync --stat should give you exact byte counts for either case.

**Comment by jonakarl** [comment]
Test with compresion:
rsync -z --stats "file" "user@server:"
Total file size: 339,719 bytes
Total bytes sent: 14,210


bz2:
rsync --stats "file".bz2 "user@server:"
Total file size: 9,133 bytes
Total bytes sent: 9,245


Multiple files (same file with three different filenames) 
rsync on 3 files: 
rsync --compress-level=9  --stats "x" "y" "z"  "user@server:"
Number of files: 3 (reg: 3)
Total file size: 1,019,157 bytes
Total bytes sent: 40,516

rsync on one big merged file:
cat x y z > w
rsync --compress-level=9  --stats "w"  "user@server:"
Number of regular files transferred: 1
Total file size: 1,019,157 bytes
Total bytes sent: 39,736

bz2:
rsync  --stats "w.bz2"  "user@server:"
Total bytes sent: 17,226

xz:
rsync  --stats "w.xz"  "user@server:"
Total bytes sent: 9,381


Conclusion: 

Most efficent compression is xz

**Comment by relet** [comment]
Is this ready to merge?

**Comment by jonakarl** [comment]
No, I need to rewrite it to use xz instead as it uses better compression. 

Is xz a dependency for this package? (ie are we ready to merge and deploy)?

**Comment by relet** [comment]
Please add dependencies as needed to the DEBIAN/control file.

**Comment by jonakarl** [comment]
I have created PR for the importer that enables on-the-fly decompression of xz files so this should be ready to roll (maybe consider removing -9) if CPU load becomes to high on the repo machine)

**Comment by relet** [comment]
I built the package and installed it on #27, you should be seeing some xz files by now.

**Pull request merged**
